version: '3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend_foodgram
    env_file: .env
    image: pierredunn/foodgram_backend
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    container_name: frontend_foodgram
    image: pierredunn/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static

  gateway:
    container_name: gateway_foodgram
    env_file: .env
    image: pierredunn/foodgram_gateway
    ports:
      - "8080:80"
    volumes:
      - static_volume:/static
      - media_volume:/app/media/
    depends_on:
      - backend
      - frontend
