version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:13.0-alpine
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend_foodgram
    env_file: ./.env
    image: pierredunn/foodgram_backend
    volumes:
      - static_volume:/app/backend_static/
      - media_volume:/app/backend_media/
    depends_on:
      - db

  frontend:
    container_name: frontend_foodgram
    image: pierredunn/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    container_name: gateway_foodgram
    env_file: ./.env
    image: nginx:1.19.3
    ports:
      - "8800:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/backend_static/
      - media_volume:/var/html/backend_media/
    depends_on:
      - backend
      - frontend